name: ci
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  release:
    types:
      - published

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          enable_go: true
      - run: npm ci
      - run: npm run build
      - run: go run ./scripts/build-archive/build-archive.go
      - name: store plugin archives
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: |
            **/*.tar.gz
            **/dist/mf-manifest.json
            !node_modules

  lint:
    name: 'lint'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: npm ci
      - run: npm run lint

  test:
    name: 'test'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: npm ci
      - run: npm run test

  type-check:
    name: 'type-check'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
      - run: npm ci
      - run: npm run type-check

  validate-schemas:
    name: 'Validate plugin schemas'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_go: true
          cue_version: 'v0.11.0'
          enable_cue: true
      - name: retrieve plugin schema dependencies
        uses: actions/download-artifact@v4
        with:
          name: plugins-schema-deps
      - run: go run ./scripts/validate-schemas/validate-schemas.go

  release:
    name: 'release'
    needs: 'build'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.release.tag_name }}
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: perses/github-actions@v0.8.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: false
          enable_go: true
      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: archives
      - run: go run ./scripts/upload-archive/upload-archive.go -tag=${{ github.event.release.tag_name }}
